In [1]:
# !pip install plotly

import plotly.graph_objects as go
import numpy as np
import pandas as pd
import scipy as sp
from sklearn import linear_model

In [2]:
exData = pd.read_csv("Ex1LS.csv")

In [3]:
X = pd.DataFrame(exData, columns=["X"])
y = pd.DataFrame(exData, columns=["Y"])
lm = linear_model.LinearRegression()
mFit = lm.fit(X,y)
exData["yhat"] = mFit.predict(X)

from sklearn.preprocessing import PolynomialFeatures 
poly = PolynomialFeatures(degree = 2) 
X_poly = poly.fit_transform(X) 
poly.fit(X_poly, y) 
lm2 =  linear_model.LinearRegression() 
mFit2 = lm2.fit(X_poly, y) 
mFit2.predict(X_poly)
exData["poly1"] = mFit2.predict(X_poly)

In [8]:
p1 = go.Figure()
p1.add_trace(go.Scatter(x=exData.X, y=exData.Y,
                    mode='markers'
                    ))
p1.add_trace(go.Scatter(x=exData.X, y=exData.yhat,
                    mode='lines',
                    line_shape='linear'
                    ))
p1.add_trace(go.Scatter(x=exData.X, y=exData.poly1,
                    mode='lines',
                    line_shape='spline'
                    ))
p1.update_layout(autosize = False, width = 500, height = 400, 
                 plot_bgcolor = '#FFFFFF')

p1.show()


In [9]:
m = np.shape(X)[0]
vY = np.array(y)
mX = np.c_[np.ones((m, 1)), np.array(X), np.array(X**2)]

beta = np.linalg.inv(np.transpose(mX).dot(mX)).dot(np.transpose(mX).dot(vY))
display(beta) # this ties!


array([[ 8.5],
       [-3.6],
       [ 1. ]])

In [10]:
mX

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.]])

In [11]:
l = np.array([0,1,10])
d  = np.identity(3)
d[0,0] = 0
d
tst = l[1]*d
tst

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
th = []
for i in range(3):
 th.append(np.linalg.inv(np.transpose(mX).dot(mX)+ (l[i] * d)).dot(np.transpose(mX).dot(vY)))

th

[array([[ 8.5],
        [-3.6],
        [ 1. ]]), array([[ 5.19354839],
        [-0.41935484],
        [ 0.38064516]]), array([[ 4.89726027e+00],
        [-1.36986301e-03],
        [ 2.80821918e-01]])]

In [13]:
th[2][0][0]

4.8972602739726